//
//  NoteDetailsWorker.swift
//  S.Kh_Task_26
//
//  Created by Saba Khitaridze on 25.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


class NoteDetailsWorker {
    
    func getNote(withId id: UUID, completion: (Result<Note, Error>) -> Void) {
        do {
            let fetchedNote = try NoteStorageManager.shared.getNote(with: id)
            guard let fetchedNote = fetchedNote else { return }
            completion(.success(fetchedNote))
        } catch {
            completion(.failure(error))
        }
    }

}
