//
//  FavoriteNotesWorker.swift
//  S.Kh_Task_26
//
//  Created by Saba Khitaridze on 25.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class FavoriteNotesWorker {
 
    func getFavoriteNotes(completion: (Result<[Note], StorageManagerError>) -> Void) {
        do {
            let favoriteNotes = try NoteStorageManager.shared.getFavoriteNotes()
            completion(.success(favoriteNotes))
        } catch {
            completion(.failure(StorageManagerError.fetchFailed))
        }
    }
}
